kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment
  namespace: flowform-app
  labels:
    app: postgres-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-api
  template:
    metadata:
      labels:
        app: postgres-api
    spec:
      containers:
        - name: api-container
          image: kushagr488/flowform-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: app-config

          command:
            - sh
            - -c
            - pnpm --filter @repo/api start
