kind: Job
apiVersion: batch/v1
metadata:
  name: migrate-db
  namespace: flowform-app
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: kushagr488/flowform-api:latest
          imagePullPolicy: Always

          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: app-config

          command:
            - sh
            - -c
            - pnpm --filter @repo/database exec drizzle-kit migrate
