name: cd

on:
  workflow_call:

jobs:
  deploy-push:
    runs-on: self-hosted
    steps:
      - name: checkout the code
        uses: actions/checkout@v7

      - name: Verify cluster
        run: kubectl get nodes
      
      - name: Creating namespace
        run: kubectl apply -f k8s/namespace.yml

      - name: Create Application Secret
        run: |
          kubectl create secret generic app-secret \
            --namespace flowform-app \
            --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --from-literal=EMAIL_USER="${{ secrets.EMAIL_USER }}" \
            --from-literal=EMAIL_PASS="${{ secrets.EMAIL_PASS }}" \
            --from-literal=EMAIL_FROM="${{ secrets.EMAIL_FROM }}" \
            --from-literal=POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
            --from-literal=POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            --from-literal=POSTGRES_DB="${{ secrets.POSTGRES_DB }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Delete old migration job
        run: |
          kubectl delete job migrate-db -n flowform-app --ignore-not-found=true 

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/

      - name: Wait for migration to complete
        run: |
          kubectl wait \
            --for=condition=complete \
            job/migrate-db \
            -n flowform-app \
            --timeout=300s

      - name: Restart API Deployment
        run: kubectl rollout restart deployment/api-deployment -n flowform-app

      - name: Wait for API rollout
        run: kubectl rollout status deployment/api-deployment -n flowform-app

      - name: Restart Web Deployment
        run: kubectl rollout restart deployment/web-deployment -n flowform-app

      - name: Wait for Web rollout
        run: kubectl rollout status deployment/web-deployment -n flowform-app