name: Ci

on:
  push:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7
      
      - name: setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9.0.0

      - name: setup node
        uses: actions/setup-node@v6
      
      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck frontend
        run: pnpm turbo typecheck --filter=web

      - name: Build frontend
        run: pnpm turbo build --filter=web
  # backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout the code
  #       uses: actions/checkout@v7

